### PR TITLE
Add ddl to cli

### PR DESCRIPTION
**Pull request by matthewmturner**
Enables the below which i think is pretty cool. Testing for this will be included in my config testing PR - i was just quite excited about this after i realized how easy it would be so wanted to get it in quick.

image

### CODE REVIEW

**Comment by matthewmturner** [comment]
@alamb FYI

**Comment by matthewmturner** [comment]
Maybe `--run-ddl` would be a better parameter name for this

**Review by alamb — COMMENTED** [review]
Does "DDL" mean run the setup scrip defined in the config files?

**Comment by matthewmturner** [comment]
Yes, it runs .config/dft/ddl.sql before running the provided command or file. It goes towards the objective of having local DB experience.

**Comment by matthewmturner** [comment]
I was excited about it because i know it will be useful for me in my day-to-day using dft. But its really not a big deal.

What would make it really cool is having a persistent catalog to use so that if you have a lot of DDL defined that you dont spend a long time running that.

**Pull request merged**
